-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."topic" add column "is_first_reply_enough" boolean
--  not null default 'false';
