-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."topic_event" add column "message_task_due_date_from_due_at" timestamptz
--  null;
