-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notification_list" add column "seen_at" timestamptz
--  not null default now();
