apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hooks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hooks
  minReplicas: 2
  maxReplicas: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 95
