apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"frontend"}}'
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
