table:
  schema: public
  name: account
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - email
        - id
        - provider_id
        - updated_at
      filter:
        user_id:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: account_updates
    definition:
      enable_manual: false
      insert:
        columns: '*'
      delete:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
