table:
  name: attachment
  schema: public
object_relationships:
- name: message
  using:
    foreign_key_constraint_on: message_id
- name: transcription
  using:
    foreign_key_constraint_on: transcription_id
insert_permissions:
- permission:
    backend_only: false
    check:
      message:
        user_id:
          _eq: X-Hasura-User-Id
    columns:
    - id
    - message_id
    - mime_type
    - original_name
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - message_id
    - mime_type
    - original_name
    - transcription_id
    - updated_at
    filter: {}
  role: user
update_permissions:
- permission:
    check: {}
    columns:
    - created_at
    - message_id
    - mime_type
    - original_name
    filter: {}
  role: user
delete_permissions:
- permission:
    filter:
      message:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    enable_manual: false
    update:
      columns:
      - mime_type
      - original_name
      - created_at
      - id
      - message_id
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: attachment_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
