table:
  name: message_reaction
  schema: public
object_relationships:
- name: message
  using:
    foreign_key_constraint_on: message_id
- name: user
  using:
    foreign_key_constraint_on: user_id
insert_permissions:
- permission:
    backend_only: false
    check:
      message:
        topic:
          _or:
          - owner_id:
              _eq: X-Hasura-User-Id
          - members:
              user_id:
                _eq: X-Hasura-User-Id
    columns:
    - emoji
    - id
    - message_id
    - user_id
  role: user
select_permissions:
- permission:
    columns:
    - emoji
    - id
    - message_id
    - updated_at
    - user_id
    filter:
      message:
        topic:
          team:
            memberships:
              user_id:
                _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - emoji
    - message_id
    - user_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
