table:
  name: notion_page
  schema: public
array_relationships:
- name: notification_notion_user_mentioneds
  using:
    foreign_key_constraint_on:
      column: notion_page_id
      table:
        name: notification_notion_user_mentioned
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      _or:
      - notification_notion_user_mentioneds:
          notification:
            user_id:
              _eq: X-Hasura-User-Id
    columns:
    - title
    - created_at
    - updated_at
    - id
  role: user
select_permissions:
- permission:
    columns:
    - id
    - title
    - created_at
    - updated_at
    filter:
      _or:
      - notification_notion_user_mentioneds:
          notification:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - title
    filter:
      _or:
      - notification_notion_user_mentioneds:
          notification:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      _or:
      - notification_notion_user_mentioneds:
          notification:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
