table:
  name: last_seen_message
  schema: public
object_relationships:
- name: message
  using:
    foreign_key_constraint_on: message_id
- name: topic
  using:
    foreign_key_constraint_on: topic_id
- name: user
  using:
    foreign_key_constraint_on: user_id
insert_permissions:
- permission:
    backend_only: false
    check:
      user_id:
        _eq: X-Hasura-User-Id
    columns:
    - id
    - message_id
    - seen_at
    - topic_id
    set:
      user_id: x-hasura-User-Id
  role: user
select_permissions:
- permission:
    columns:
    - id
    - message_id
    - seen_at
    - topic_id
    - updated_at
    - user_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - message_id
    - seen_at
    - topic_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
    set:
      user_id: x-hasura-User-Id
  role: user
