table:
  name: user_slack_channels_by_team
  schema: public
object_relationships:
- name: user
  using:
    foreign_key_constraint_on: user_id
- name: user_slack_installation
  using:
    foreign_key_constraint_on: user_slack_installation_id
insert_permissions:
- permission:
    backend_only: false
    check:
      user_id:
        _eq: X-Hasura-User-Id
    columns:
    - created_at
    - id
    - included_channels
    - slack_workspace_id
    - updated_at
    - user_id
    - user_slack_installation_id
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - included_channels
    - slack_workspace_id
    - updated_at
    - user_id
    - user_slack_installation_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - included_channels
    - updated_at
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
