table:
  name: team_slack_installation
  schema: public
object_relationships:
- name: team
  using:
    foreign_key_constraint_on: team_id
computed_fields:
- definition:
    function:
      name: team_slack_installation_scopes
      schema: public
  name: scopes
select_permissions:
- permission:
    columns:
    - id
    - team_id
    - updated_at
    computed_fields:
    - scopes
    filter:
      team:
        memberships:
          user_id:
            _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: false
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: team_slack_installation_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
