table:
  schema: public
  name: github_account_to_installation
object_relationships:
  - name: github_account
    using:
      foreign_key_constraint_on: user_id
  - name: github_installation
    using:
      foreign_key_constraint_on: installation_id
event_triggers:
  - name: github_account_to_installation_updates
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
