table:
  name: room_member
  schema: public
object_relationships:
- name: room
  using:
    foreign_key_constraint_on: room_id
- name: user
  using:
    foreign_key_constraint_on: user_id
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: false
    insert:
      columns: "*"
    update:
      columns:
      - room_id
      - user_id
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: room_member_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
