table:
  name: notification
  schema: public
object_relationships:
- name: slack_mention
  using:
    manual_configuration:
      column_mapping:
        id: notification_id
      insertion_order: null
      remote_table:
        name: notification_slack_mention
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      user_id:
        _eq: X-Hasura-User-Id
    columns:
    - url
    - created_at
    - resolved_at
    - updated_at
    - id
    - user_id
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - resolved_at
    - updated_at
    - url
    - user_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - resolved_at
    - updated_at
    - url
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
