table:
  schema: public
  name: asana_account
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - id
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
