table:
  schema: public
  name: alert_read_receipt
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - alert_id
        - user_id
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - alert_id
        - id
        - read_at
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
