table:
  name: transcription
  schema: public
array_relationships:
  - name: attachments
    using:
      foreign_key_constraint_on:
        column: transcription_id
        table:
          name: attachment
          schema: public
select_permissions:
  - permission:
      columns:
        - created_at
        - id
        - status
        - transcript
        - updated_at
      filter:
        attachments:
          message:
            topic:
              room:
                members:
                  user_id:
                    _eq: X-Hasura-User-Id
    role: user
event_triggers:
  - definition:
      delete:
        columns: "*"
      enable_manual: false
      insert:
        columns: "*"
      update:
        columns:
          - updated_at
          - id
          - sonix_media_id
          - status
          - transcript
          - created_at
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
    name: transcription_updates
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
