table:
  name: notification_linear
  schema: public
object_relationships:
- name: notification
  using:
    foreign_key_constraint_on: notification_id
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - issue_id
    - issue_title
    - notification_id
    - type
    - updated_at
    filter:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
