table:
  name: topic_member
  schema: public
object_relationships:
- name: topic
  using:
    foreign_key_constraint_on: topic_id
- name: user
  using:
    foreign_key_constraint_on: user_id
select_permissions:
- permission:
    columns:
    - id
    - topic_id
    - user_id
    - created_at
    - updated_at
    filter:
      topic:
        _or:
        - owner_id:
            _eq: X-Hasura-User-Id
        - members:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    enable_manual: false
    insert:
      columns: "*"
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: topic_member_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
