table:
  name: notification_figma_comment
  schema: public
object_relationships:
- name: notification
  using:
    foreign_key_constraint_on: notification_id
insert_permissions:
- permission:
    backend_only: false
    check:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
    columns:
    - created_at
    - figma_notification_id
    - file_id
    - file_name
    - id
    - is_mention
    - notification_id
    - thread_comment_id
    - updated_at
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - figma_notification_id
    - file_id
    - file_name
    - id
    - is_mention
    - notification_id
    - thread_comment_id
    - updated_at
    filter:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - file_name
    - updated_at
    filter:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
