table:
  name: message_task_due_date
  schema: public
object_relationships:
- name: message
  using:
    foreign_key_constraint_on: message_id
insert_permissions:
- permission:
    backend_only: false
    check:
      _or:
      - message:
          topic:
            owner_id:
              _eq: X-Hasura-User-Id
      - message:
          topic:
            members:
              user_id:
                _eq: X-Hasura-User-Id
    columns:
    - created_at
    - due_at
    - id
    - message_id
    - updated_at
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - due_at
    - updated_at
    - id
    - message_id
    filter:
      _or:
      - message:
          topic:
            owner_id:
              _eq: X-Hasura-User-Id
      - message:
          topic:
            members:
              user_id:
                _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - due_at
    filter:
      _or:
      - message:
          topic:
            owner_id:
              _eq: X-Hasura-User-Id
      - message:
          topic:
            members:
              user_id:
                _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      _or:
      - message:
          topic:
            owner_id:
              _eq: X-Hasura-User-Id
      - message:
          topic:
            members:
              user_id:
                _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    enable_manual: false
    insert:
      columns: "*"
    update:
      columns:
      - created_at
      - due_at
      - updated_at
      - id
      - message_id
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: message_task_due_date_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
