table:
  schema: public
  name: notification_jira_issue
object_relationships:
  - name: notification
    using:
      foreign_key_constraint_on: notification_id
  - name: notification_jira_issue_type
    using:
      foreign_key_constraint_on: type
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - from
        - id
        - issue_id
        - issue_title
        - notification_id
        - to
        - type
        - updated_at
        - updated_issue_field
      filter:
        notification:
          user_id:
            _eq: X-Hasura-User-Id
