table:
  schema: public
  name: linear_issue
event_triggers:
  - name: linear_issue_updates
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
