table:
  schema: public
  name: clickup_team
array_relationships:
  - name: accounts
    using:
      foreign_key_constraint_on:
        column: team_id
        table:
          schema: public
          name: clickup_account_to_team
select_permissions:
  - role: user
    permission:
      columns:
        - clickup_team_id
        - created_at
        - id
        - name
        - updated_at
      filter:
        accounts:
          clickup_account:
            user_id:
              _eq: X-Hasura-User-Id
