table:
  name: notification_slack_message
  schema: public
object_relationships:
- name: notification
  using:
    foreign_key_constraint_on: notification_id
select_permissions:
- permission:
    columns:
    - conversation_name
    - created_at
    - id
    - is_mention
    - is_private_conversation
    - notification_id
    - slack_conversation_id
    - slack_message_ts
    - slack_thread_ts
    - updated_at
    filter:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
