table:
  schema: public
  name: notification
object_relationships:
  - name: slack_mention
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: notification_slack_message
        insertion_order: null
        column_mapping:
          id: notification_id
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - created_at
        - from
        - id
        - last_preloaded_at
        - last_seen_at
        - notified_user_at
        - resolved_at
        - saved_at
        - snoozed_until
        - text_preview
        - updated_at
        - url
        - user_id
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - from
        - id
        - last_preloaded_at
        - last_seen_at
        - notified_user_at
        - resolved_at
        - saved_at
        - snoozed_until
        - text_preview
        - updated_at
        - url
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - last_preloaded_at
        - last_seen_at
        - notified_user_at
        - resolved_at
        - saved_at
        - snoozed_until
        - text_preview
        - updated_at
        - url
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
event_triggers:
  - name: notification_updates
    definition:
      enable_manual: false
      update:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
