table:
  name: topic
  schema: public
object_relationships:
- name: closed_by_user
  using:
    manual_configuration:
      column_mapping:
        closed_by_user_id: id
      insertion_order: null
      remote_table:
        name: user
        schema: public
- name: owner
  using:
    foreign_key_constraint_on: owner_id
- name: team
  using:
    manual_configuration:
      column_mapping:
        team_id: id
      insertion_order: null
      remote_table:
        name: team
        schema: public
array_relationships:
- name: last_seen_messages
  using:
    foreign_key_constraint_on:
      column: topic_id
      table:
        name: last_seen_message
        schema: public
- name: members
  using:
    foreign_key_constraint_on:
      column: topic_id
      table:
        name: topic_member
        schema: public
- name: messages
  using:
    manual_configuration:
      column_mapping:
        id: topic_id
      insertion_order: null
      remote_table:
        name: message
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      _or:
      - team:
          memberships:
            user_id:
              _eq: X-Hasura-User-Id
      - owner_id:
          _eq: X-Hasura-User-Id
    columns:
    - archived_at
    - closed_at
    - closed_by_user_id
    - id
    - index
    - name
    - owner_id
    - priority
    - slug
    - team_id
  role: user
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - archived_at
    - closed_at
    - closed_by_user_id
    - created_at
    - id
    - index
    - name
    - owner_id
    - priority
    - slug
    - team_id
    - updated_at
    filter:
      _or:
      - members:
          user_id:
            _eq: X-Hasura-User-Id
      - owner_id:
          _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - archived_at
    - closed_at
    - closed_by_user_id
    - index
    - name
    - owner_id
    - priority
    - slug
    filter:
      _or:
      - members:
          user_id:
            _eq: X-Hasura-User-Id
      - owner_id:
          _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      owner_id:
        _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: false
    insert:
      columns: "*"
    update:
      columns:
      - index
      - name
      - slug
      - archived_at
      - closed_at
      - updated_at
      - closed_by_user_id
      - id
      - owner_id
      - team_id
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: topic_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
