table:
  name: user_group_member
  schema: public
object_relationships:
- name: user_group
  using:
    foreign_key_constraint_on: user_group_id
insert_permissions:
- permission:
    backend_only: false
    check:
      user_group:
        team:
          memberships:
            user_id:
              _eq: X-Hasura-User-Id
    columns:
    - id
    - created_at
    - updated_at
    - user_group_id
    - user_id
  role: user
select_permissions:
- permission:
    columns:
    - id
    - created_at
    - updated_at
    - user_group_id
    - user_id
    filter:
      user_group:
        team:
          memberships:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - updated_at
    filter:
      user_group:
        team:
          memberships:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_group:
        team:
          memberships:
            user_id:
              _eq: X-Hasura-User-Id
  role: user
