table:
  name: notification
  schema: public
object_relationships:
- name: slack_mention
  using:
    manual_configuration:
      column_mapping:
        id: notification_id
      insertion_order: null
      remote_table:
        name: notification_slack_message
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      user_id:
        _eq: X-Hasura-User-Id
    columns:
    - created_at
    - from
    - id
    - last_seen_at
    - notified_user_at
    - resolved_at
    - snoozed_until
    - text_preview
    - updated_at
    - url
    - user_id
    - was_auto_resolved
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - from
    - id
    - last_seen_at
    - notified_user_at
    - resolved_at
    - snoozed_until
    - text_preview
    - updated_at
    - url
    - user_id
    - was_auto_resolved
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - from
    - last_seen_at
    - notified_user_at
    - resolved_at
    - snoozed_until
    - text_preview
    - updated_at
    - url
    - was_auto_resolved
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
