table:
  schema: public
  name: github_installation
array_relationships:
  - name: github_account_to_installations
    using:
      foreign_key_constraint_on:
        column: installation_id
        table:
          schema: public
          name: github_account_to_installation
select_permissions:
  - role: user
    permission:
      columns:
        - account_id
        - account_login
        - created_at
        - id
        - installation_id
        - repository_selection
        - target_type
        - updated_at
      filter:
        github_account_to_installations:
          user_id:
            _eq: X-Hasura-User-Id
