table:
  name: notification_list
  schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      user_id:
        _eq: X-Hasura-User-Id
    columns:
    - created_at
    - filters
    - id
    - notifications_interval_ms
    - seen_at
    - title
    - updated_at
    - user_id
  role: user
select_permissions:
- permission:
    columns:
    - created_at
    - filters
    - id
    - notifications_interval_ms
    - seen_at
    - title
    - updated_at
    - user_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - created_at
    - filters
    - id
    - notifications_interval_ms
    - seen_at
    - title
    - updated_at
    - user_id
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
