table:
  schema: public
  name: notification_list
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - created_at
        - emoji
        - filters
        - id
        - notifications_interval_ms
        - seen_at
        - system_id
        - title
        - updated_at
        - user_id
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - emoji
        - filters
        - id
        - notifications_interval_ms
        - seen_at
        - system_id
        - title
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - emoji
        - filters
        - id
        - notifications_interval_ms
        - seen_at
        - title
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _and:
          - user_id:
              _eq: X-Hasura-User-Id
          - system_id:
              _is_null: true
