table:
  schema: public
  name: gmail_account
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - id
        - updated_at
      filter:
        account:
          user_id:
            _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      filter:
        account:
          user_id:
            _eq: X-Hasura-User-Id
event_triggers:
  - name: gmail_account_updates
    definition:
      enable_manual: false
      delete:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
