table:
  name: user_slack_installation
  schema: public
computed_fields:
- definition:
    function:
      name: get_user_slack_installation_slack_team_id
      schema: public
  name: slack_team_id
- definition:
    function:
      name: user_slack_installation_user_scopes
      schema: public
  name: user_scopes
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - updated_at
    - user_id
    computed_fields:
    - slack_team_id
    - user_scopes
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
