table:
  name: gmail_account
  schema: public
object_relationships:
- name: account
  using:
    foreign_key_constraint_on: account_id
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - updated_at
    filter:
      account:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      account:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: false
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: gmail_account_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
