table:
  name: team_member_slack
  schema: public
object_relationships:
- name: team_member
  using:
    foreign_key_constraint_on: team_member_id
computed_fields:
- definition:
    function:
      name: team_member_slack_scopes
      schema: public
  name: slack_scopes
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - slack_user_id
    - team_member_id
    - updated_at
    computed_fields:
    - slack_scopes
    filter:
      team_member:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: false
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: team_member_slack_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
