table:
  name: message_reaction
  schema: public
object_relationships:
  - name: message
    using:
      foreign_key_constraint_on: message_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - permission:
      backend_only: false
      check: {}
      columns:
        - emoji
        - message_id
        - user_id
    role: user
select_permissions:
  - permission:
      columns:
        - created_at
        - emoji
        - message_id
        - user_id
      filter: {}
    role: user
update_permissions:
  - permission:
      check: null
      columns:
        - emoji
        - message_id
        - user_id
      filter: {}
    role: user
delete_permissions:
  - permission:
      filter: {}
    role: user
