table:
  schema: public
  name: user_slack_channels_by_team
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
  - name: user_slack_installation
    using:
      foreign_key_constraint_on: user_slack_installation_id
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - are_bots_enabled
        - created_at
        - id
        - included_channels
        - slack_workspace_id
        - updated_at
        - user_id
        - user_slack_installation_id
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - are_bots_enabled
        - created_at
        - id
        - included_channels
        - slack_workspace_id
        - updated_at
        - user_id
        - user_slack_installation_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - are_bots_enabled
        - included_channels
        - updated_at
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
