table:
  name: linear_issue
  schema: public
event_triggers:
- definition:
    enable_manual: false
    insert:
      columns: "*"
    update:
      columns: "*"
  headers:
  - name: Authorization
    value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  name: linear_issue_updates
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
