table:
  schema: public
  name: user_slack_channels_by_team
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
  - name: user_slack_installation
    using:
      foreign_key_constraint_on: user_slack_installation_id
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - are_all_channels_included
        - are_bots_enabled
        - created_at
        - excluded_channels
        - id
        - included_channels
        - slack_workspace_id
        - updated_at
        - user_id
        - user_slack_installation_id
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - are_all_channels_included
        - are_bots_enabled
        - created_at
        - excluded_channels
        - id
        - included_channels
        - slack_workspace_id
        - updated_at
        - user_id
        - user_slack_installation_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - are_all_channels_included
        - are_bots_enabled
        - excluded_channels
        - included_channels
        - updated_at
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: channel_filter_migration
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - are_all_channels_included
          - included_channels
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
