table:
  name: team_invitation
  schema: public
object_relationships:
- name: inviting_user
  using:
    foreign_key_constraint_on: inviting_user_id
- name: team
  using:
    foreign_key_constraint_on: team_id
insert_permissions:
- permission:
    backend_only: false
    check:
      team:
        memberships:
          user_id:
            _eq: X-Hasura-User-Id
    columns:
    - created_at
    - id
    - updated_at
    set:
      inviting_user_id: x-hasura-User-Id
  role: user
select_permissions:
- permission:
    columns: []
    filter: {}
  role: public
- permission:
    columns:
    - created_at
    - id
    - inviting_user_id
    - updated_at
    filter:
      team:
        memberships:
          user_id:
            _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      team:
        memberships:
          user_id:
            _eq: X-Hasura-User-Id
  role: user
