table:
  name: notification_slack_mention
  schema: public
object_relationships:
- name: notification
  using:
    foreign_key_constraint_on: notification_id
select_permissions:
- permission:
    columns:
    - channel_name
    - created_at
    - from
    - id
    - is_private_message
    - notification_id
    - slack_conversation_id
    - slack_message_ts
    - updated_at
    filter:
      notification:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
