table:
  name: notification
  schema: public
object_relationships:
- name: user
  using:
    foreign_key_constraint_on: user_id
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - created_at
    - id
    - read_at
    - user_id
    - updated_at
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - read_at
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
