table:
  name: user
  schema: public
object_relationships:
- name: current_team
  using:
    foreign_key_constraint_on: current_team_id
array_relationships:
- name: created_team_invitations
  using:
    foreign_key_constraint_on:
      column: inviting_user_id
      table:
        name: team_invitation
        schema: public
- name: messages
  using:
    manual_configuration:
      column_mapping:
        id: user_id
      insertion_order: null
      remote_table:
        name: message
        schema: public
- name: notifications
  using:
    foreign_key_constraint_on:
      column: user_id
      table:
        name: notification
        schema: public
- name: owned_teams
  using:
    foreign_key_constraint_on:
      column: owner_id
      table:
        name: team
        schema: public
- name: space_memberships
  using:
    foreign_key_constraint_on:
      column: user_id
      table:
        name: space_member
        schema: public
- name: team_memberships
  using:
    foreign_key_constraint_on:
      column: user_id
      table:
        name: team_member
        schema: public
- name: topic_memberships
  using:
    foreign_key_constraint_on:
      column: user_id
      table:
        name: topic_member
        schema: public
select_permissions:
- permission:
    columns:
    - avatar_url
    - email
    - id
    - name
    - updated_at
    filter:
      _or:
      - team_memberships:
          team:
            memberships:
              user_id:
                _eq: X-Hasura-User-Id
      - messages:
          topic:
            team:
              memberships:
                user_id:
                  _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - avatar_url
    - current_team_id
    - name
    filter:
      id:
        _eq: X-Hasura-User-Id
  role: user
