table:
  schema: public
  name: notion_space
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: created_by
insert_permissions:
  - role: user
    permission:
      check:
        user:
          id:
            _eq: X-Hasura-User-Id
      columns:
        - created_at
        - created_by
        - id
        - name
        - space_id
        - updated_at
      backend_only: false
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - created_by
        - id
        - name
        - space_id
        - updated_at
      filter: {}
