table:
  schema: public
  name: alert_read_receipt
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - read_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
