table:
  schema: public
  name: user
object_relationships:
  - name: current_team
    using:
      foreign_key_constraint_on: current_team_id
array_relationships:
  - name: owned_teams
    using:
      foreign_key_constraint_on:
        column: owner_id
        table:
          schema: public
          name: team
  - name: team_memberships
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          schema: public
          name: team_member
computed_fields:
  - name: count_referrals
    definition:
      function:
        schema: public
        name: count_user_referrals
    comment: ""
  - name: has_account
    definition:
      function:
        schema: public
        name: has_user_account
  - name: has_slack_installation
    definition:
      function:
        schema: public
        name: has_slack_installation
select_permissions:
  - role: user
    permission:
      columns:
        - avatar_url
        - created_at
        - email
        - id
        - is_bot
        - is_slack_auto_resolve_enabled
        - name
        - onboarding_finished_at
        - referral_code
        - slack_included_channels
        - subscription_plan
        - updated_at
      computed_fields:
        - count_referrals
        - has_account
        - has_slack_installation
      filter:
        _or:
          - team_memberships:
              team:
                memberships:
                  user_id:
                    _eq: X-Hasura-User-Id
          - id:
              _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - avatar_url
        - current_team_id
        - is_slack_auto_resolve_enabled
        - name
        - onboarding_finished_at
        - slack_included_channels
      filter:
        id:
          _eq: X-Hasura-User-Id
      check: null
event_triggers:
  - name: user_signup
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
  - name: user_updates
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - avatar_url
          - email
          - name
          - created_at
          - email_verified
          - updated_at
          - current_team_id
          - id
          - onboarding_finished_at
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
    headers:
      - name: Authorization
        value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
