table:
  name: user_slack_installation
  schema: public
computed_fields:
- definition:
    function:
      name: user_slack_installation_team_id
      schema: public
  name: team_id
- definition:
    function:
      name: user_slack_installation_team_name
      schema: public
  name: team_name
- definition:
    function:
      name: user_slack_installation_user_scopes
      schema: public
  name: user_scopes
select_permissions:
- permission:
    columns:
    - created_at
    - id
    - slack_team_id
    - slack_user_id
    - updated_at
    - user_id
    computed_fields:
    - team_id
    - team_name
    - user_scopes
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
delete_permissions:
- permission:
    filter:
      user_id:
        _eq: X-Hasura-User-Id
  role: user
