-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."team_slack_installation" add column "slack_team_id" text
--  null;
