apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: test
  labels:
    app: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      serviceAccountName: gsm
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.19.2
          command:
            [
              "/cloud_sql_proxy",
              "-ip_address_types=PRIVATE",
              "-instances=meetnomoreapp:europe-west1:$(INSTANCE_NAME)=tcp:5432",
            ]
          envFrom:
            - configMapRef:
                name: cloudsql-proxy-config
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 2 # non-root user
        - name: graphql-engine
          image: eu.gcr.io/meetnomoreapp/graphql-engine:1.3.3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hasura-config
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          imagePullPolicy: Always
