apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: test
  labels:
    app: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      serviceAccountName: gsm
      containers:
        - name: graphql-engine
          image: eu.gcr.io/meetnomoreapp/graphql-engine:2.1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hasura-config
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 3
          imagePullPolicy: Always
