apiVersion: v1
kind: Service
metadata:
  name: hasura
  namespace: test
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"hasura"}}'
spec:
  type: NodePort
  selector:
    app: hasura
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
