-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user" add column "slack_included_channels" jsonb
--  not null default '[]';
