-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."slack_notification_queue" add column "payload" jsonb
--  not null;
