# default configuration, runs in dev mode. Environment variable and different environments (prod, test) can override this
# Check out custom-environment-variables.yaml
# more info: https://github.com/lorenwest/node-config

firebase:
  databaseUrl: https://meetnomoreapp.firebaseio.com

# overridden from secrets
database:
  user: user
  password: dev
  name: dev_db
  host:
    socketPath: localhost
    connection: ""

hasura:
  eventSecret: dev-event-secret # used to authenticate calls from hasura events to backend
  queryApi:
    url: http://localhost:8080/v1/query
    secret: dev
    role: admin
  actionSecret: dev-action-secret # used to authenticate calls from hasura actions to backend
  notificationSecret: dev-notification-secret

logging:
  level: info

port: 1337

backend:
  rootUrl: http://localhost:1337
  authToken: dev-auth-token

sendgrid:
  apiKey: SG.fakeApiKey

app:
  url: http://localhost:3000
