# default configuration, runs in dev mode. Environment variable and different environments (prod, test) can override this
# Check out custom-environment-variables.yaml
# more info: https://github.com/lorenwest/node-config

firebase:
  databaseUrl: https://meetnomoreapp.firebaseio.com

# overridden from secrets
database:
  user: user
  password: dev
  name: dev_db
  host:
    socketPath: localhost
    connection: ""

logging:
  level: info

# What google secret manager secrets to use in production and what config properties to map them to
secrets:
  "database.user": DB_USER
  "database.password": DB_PASSWORD
  "database.name": DB_NAME

port: 1337
