# Production-specific configuration properties.

logging:
  level: info

database:
  host:
    socketPath: /cloudsql
    connection: meetnomoreapp:europe-west1:howl-database

overrides:
  environmentVariables:
    "port": PORT

  googleCloudSecrets:
    "database.user": DB_USER
    "database.password": DB_PASSWORD
    "database.name": DB_NAME
    "hasura.eventSecret": HASURA_EVENT_SECRET
    "hasura.actionSecret": HASURA_ACTION_SECRET
