# Production-specific configuration properties.

logging:
  level: info

database:
  host:
    socketPath: /cloudsql

overrides:
  environmentVariables:
    "port": PORT

  googleCloudSecrets:
    "database.user": DB_USER
    "database.password": DB_PASSWORD
    "database.name": DB_NAME
