-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.dedupe_topic_slug()
--  RETURNS trigger
--  LANGUAGE plpgsql
-- AS $function$
-- DECLARE
--   i INT := 2;
--   chosen_slug TEXT := NEW.slug;
-- BEGIN
--   WHILE EXISTS(SELECT * FROM topic WHERE team_id = NEW.team_id AND slug = NEW.slug)
--     LOOP
--       NEW.slug = chosen_slug || '-' || i;
--       i = i + 1;
--     END LOOP;
--
--   RETURN NEW;
-- END;
-- $function$;
