apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: test
  labels:
    app: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: gsm
      terminationGracePeriodSeconds: 15
      containers:
        - name: backend
          image: eu.gcr.io/meetnomoreapp/monorepo:4.213.0
          command: ["./scripts/start.sh"]
          resources:
            requests:
              cpu: 400m
            limits:
              memory: 1.5Gi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-default
          env:
            - name: BACKEND_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              port: 8080
              path: /healthz
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 15
