apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: test
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: gsm
      containers:
        - name: backend
          image: eu.gcr.io/meetnomoreapp/monorepo:3.133.1
          command: ["yarn", "run", "start:backend"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-default
          env:
            - name: BACKEND_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 10
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.27.0
          command:
            [
              "/cloud_sql_proxy",
              "-ip_address_types=PRIVATE",
              "-instances=meetnomoreapp:europe-west1:$(CLOUDSQL_INSTANCE_NAME)=tcp:5432",
              "-structured_logs",
              "-use_http_health_check",
            ]
          envFrom:
            - configMapRef:
                name: api-default
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8090
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8090
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          startupProbe:
            httpGet:
              path: /startup
              port: 8090
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 20
