apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: test
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"api"}}'
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
