-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notification_jira_issue" add column "updated_issue_field" text
--  null;
