-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user" add column "is_slack_auto_resolve_enabled" boolean
--  not null default 'False';
