- name: update-atlassian-refresh-token
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: '* * 1 * *'
  include_in_metadata: true
  payload:
    handler: update-atlassian-refresh-token
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
