- name: auto-archive-or-close-topics
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 1 * * * *
  include_in_metadata: true
  payload:
    handler: auto-archive-or-close-topics
  retry_conf:
    num_retries: 1
    timeout_seconds: 60
    tolerance_seconds: 21600
    retry_interval_seconds: 10
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: daily-message-notification
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 5 * * * 1-5
  include_in_metadata: true
  payload:
    handler: daily-message-notification
  retry_conf:
    num_retries: 1
    timeout_seconds: 60
    tolerance_seconds: 21600
    retry_interval_seconds: 10
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: delayed-topic-requests-done-notification
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: '*/15 * * * *'
  include_in_metadata: true
  payload:
    handler: delayed-topic-requests-done-notification
  retry_conf:
    num_retries: 1
    timeout_seconds: 60
    tolerance_seconds: 21600
    retry_interval_seconds: 10
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: proactive-notifications
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: '*/15 * * * *'
  include_in_metadata: true
  payload:
    handler: proactive-notifications
  retry_conf:
    num_retries: 1
    timeout_seconds: 60
    tolerance_seconds: 21600
    retry_interval_seconds: 10
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: refresh-expiring-atlassian-properties
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 0 3 * * *
  include_in_metadata: true
  payload:
    handler: refresh-expiring-atlassian-properties
  headers:
  - name: Authorization
    value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
