- name: cleanup-processed-messages
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 30 * * * *
  include_in_metadata: true
  payload:
    handler: cleanup-processed-messages
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: mark-read-slack-messages
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: '* * * * *'
  include_in_metadata: true
  payload:
    handler: mark-read-slack-messages
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: mark-resolved-slack-conversations-as-read
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: '* * * * *'
  include_in_metadata: true
  payload:
    handler: mark-slack-conversations-as-read
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: renew-gmail-watchers
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 0 15 * * *
  include_in_metadata: true
  payload:
    handler: renew-gmail-watchers
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: sync-slack-teams
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 0 * 10 * *
  include_in_metadata: true
  payload:
    handler: sync-slack-teams
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
- name: update-atlassian-refresh-token
  webhook: '{{HASURA_CRON_WEBHOOK_URL}}'
  schedule: 0 * 15 * *
  include_in_metadata: true
  payload:
    handler: update-atlassian-refresh-token
  headers:
    - name: Authorization
      value_from_env: HASURA_ACTIONS_WEBHOOK_AUTHORIZATION_HEADER
