- function:
    schema: public
    name: delete_single_team_slack_installation
  configuration:
    exposed_as: mutation
  permissions:
    - role: user
- function:
    schema: public
    name: search_full_text
- function:
    schema: public
    name: search_full_text_topic
