- table:
    schema: public
    name: account
  object_relationships:
    - name: user
      using:
        foreign_key_constraint_on: user_id
- table:
    schema: public
    name: attachment
  insert_permissions:
    - role: user
      permission:
        check: {}
        columns: []
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - created_at
          - id
          - mime_type
          - original_name
        filter: {}
  update_permissions:
    - role: user
      permission:
        columns: []
        filter: {}
        check: null
  delete_permissions:
    - role: user
      permission:
        filter: {}
- table:
    schema: public
    name: full_text_search
  select_permissions:
    - role: user
      permission:
        columns:
          - room_id
          - room_name
          - user_id
          - topic_id
          - topic_name
          - message_created_at
          - message_type
          - message_id
          - message_content
          - transcription_id
          - attachment_id
          - attachment_name
          - transcript
        filter:
          user_id:
            _eq: X-Hasura-User-Id
- table:
    schema: public
    name: last_seen_message
  insert_permissions:
    - role: user
      permission:
        check:
          user_id:
            _eq: X-Hasura-User-Id
        set:
          user_id: x-hasura-User-Id
        columns:
          - message_id
          - topic_id
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - message_id
          - seen_at
          - topic_id
        filter:
          user_id:
            _eq: X-Hasura-User-Id
  update_permissions:
    - role: user
      permission:
        columns:
          - message_id
          - topic_id
        filter:
          user_id:
            _eq: X-Hasura-User-Id
        check: null
        set:
          user_id: x-hasura-User-Id
- table:
    schema: public
    name: message
  object_relationships:
    - name: message_type
      using:
        foreign_key_constraint_on: type
    - name: topic
      using:
        foreign_key_constraint_on: topic_id
    - name: transcription
      using:
        foreign_key_constraint_on: transcription_id
    - name: user
      using:
        foreign_key_constraint_on: user_id
  array_relationships:
    - name: message_attachments
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: message_attachments
          column_mapping:
            id: message_id
  insert_permissions:
    - role: user
      permission:
        check:
          topic:
            room:
              _and:
                - finished_at:
                    _is_null: true
                - participants:
                    user_id:
                      _eq: X-Hasura-User-Id
        set:
          user_id: x-hasura-User-Id
        columns:
          - is_draft
          - content
          - is_draft
          - topic_id
          - type
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - content
          - created_at
          - id
          - is_draft
          - topic_id
          - type
          - user_id
        filter:
          topic:
            room:
              participants:
                user_id:
                  _eq: X-Hasura-User-Id
        allow_aggregations: true
  update_permissions:
    - role: user
      permission:
        columns:
          - is_draft
          - content
        filter:
          user_id:
            _eq: X-Hasura-User-Id
        check: null
  delete_permissions:
    - role: user
      permission:
        filter:
          user_id:
            _eq: X-Hasura-User-Id
  event_triggers:
    - name: message_created
      definition:
        enable_manual: false
        insert:
          columns: "*"
      retry_conf:
        num_retries: 5
        interval_sec: 10
        timeout_sec: 30
      webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
      headers:
        - name: Authorization
          value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
- table:
    schema: public
    name: message_attachments
  object_relationships:
    - name: attachment
      using:
        foreign_key_constraint_on: attachment_id
    - name: message
      using:
        foreign_key_constraint_on: message_id
  insert_permissions:
    - role: user
      permission:
        check: {}
        columns:
          - message_id
          - attachment_id
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - attachment_id
          - message_id
        filter: {}
  update_permissions:
    - role: user
      permission:
        columns:
          - attachment_id
          - message_id
        filter: {}
        check: null
  delete_permissions:
    - role: user
      permission:
        filter: {}
- table:
    schema: public
    name: message_full_text
- table:
    schema: public
    name: message_type
  is_enum: true
  select_permissions:
    - role: user
      permission:
        columns:
          - value
        filter: {}
- table:
    schema: public
    name: room
  object_relationships:
    - name: creator
      using:
        foreign_key_constraint_on: creator_id
    - name: space
      using:
        foreign_key_constraint_on: space_id
  array_relationships:
    - name: participants
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: room_participants
          column_mapping:
            id: room_id
    - name: room_invites
      using:
        foreign_key_constraint_on:
          column: room_id
          table:
            schema: public
            name: room_invites
    - name: topics
      using:
        foreign_key_constraint_on:
          column: room_id
          table:
            schema: public
            name: topic
  insert_permissions:
    - role: user
      permission:
        check: {}
        set:
          creator_id: x-hasura-User-Id
        columns:
          - deadline
          - name
          - space_id
          - summary
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - created_at
          - creator_id
          - deadline
          - finished_at
          - id
          - name
          - space_id
          - summary
        filter:
          participants:
            user_id:
              _eq: X-Hasura-User-Id
  update_permissions:
    - role: user
      permission:
        columns:
          - deadline
          - finished_at
          - name
          - summary
        filter:
          participants:
            user_id:
              _eq: X-Hasura-User-Id
        check: null
  delete_permissions:
    - role: user
      permission:
        filter:
          participants:
            user_id:
              _eq: X-Hasura-User-Id
  event_triggers:
    - name: room_created
      definition:
        enable_manual: false
        insert:
          columns: "*"
      retry_conf:
        num_retries: 5
        interval_sec: 10
        timeout_sec: 60
      webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
      headers:
        - name: Authorization
          value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
- table:
    schema: public
    name: room_invites
  object_relationships:
    - name: inviter
      using:
        foreign_key_constraint_on: inviter_id
    - name: room
      using:
        foreign_key_constraint_on: room_id
  insert_permissions:
    - role: user
      permission:
        check:
          room:
            creator_id:
              _eq: X-Hasura-User-Id
        set:
          inviter_id: x-hasura-User-Id
        columns:
          - email
          - room_id
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - used_at
          - created_at
          - email
          - id
          - inviter_id
          - room_id
        filter:
          room:
            creator_id:
              _eq: X-Hasura-User-Id
  event_triggers:
    - name: invite_created
      definition:
        enable_manual: false
        insert:
          columns: "*"
      retry_conf:
        num_retries: 5
        interval_sec: 100
        timeout_sec: 600
      webhook_from_env: HASURA_EVENTS_WEBHOOK_URL
      headers:
        - name: Authorization
          value_from_env: HASURA_EVENTS_WEBHOOK_AUTHORIZATION_HEADER
- table:
    schema: public
    name: room_participants
  object_relationships:
    - name: room
      using:
        foreign_key_constraint_on: room_id
    - name: user
      using:
        foreign_key_constraint_on: user_id
  select_permissions:
    - role: user
      permission:
        columns:
          - room_id
          - user_id
        filter:
          room:
            participants:
              user_id:
                _eq: X-Hasura-User-Id
- table:
    schema: public
    name: space
  object_relationships:
    - name: creator
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: user
          column_mapping:
            creator_id: id
  array_relationships:
    - name: participants
      using:
        foreign_key_constraint_on:
          column: space_id
          table:
            schema: public
            name: space_participants
    - name: rooms
      using:
        foreign_key_constraint_on:
          column: space_id
          table:
            schema: public
            name: room
  insert_permissions:
    - role: user
      permission:
        check: {}
        set:
          creator_id: x-hasura-User-Id
        columns:
          - name
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - creator_id
          - id
          - name
        filter:
          _or:
            - creator_id:
                _eq: X-Hasura-User-Id
            - participants:
                user_id:
                  _eq: X-Hasura-User-Id
  update_permissions:
    - role: user
      permission:
        columns: []
        filter:
          _or:
            - creator_id:
                _eq: X-Hasura-User-Id
            - participants:
                user_id:
                  _eq: X-Hasura-User-Id
        check: null
  delete_permissions:
    - role: user
      permission:
        filter:
          _or:
            - creator_id:
                _eq: X-Hasura-User-Id
            - participants:
                user_id:
                  _eq: X-Hasura-User-Id
- table:
    schema: public
    name: space_participants
  object_relationships:
    - name: space
      using:
        foreign_key_constraint_on: space_id
    - name: user
      using:
        foreign_key_constraint_on: user_id
  insert_permissions:
    - role: user
      permission:
        check:
          space:
            _or:
              - creator_id:
                  _eq: X-Hasura-User-Id
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
        columns: []
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns: []
        filter:
          space:
            _or:
              - creator_id:
                  _eq: X-Hasura-User-Id
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
  update_permissions:
    - role: user
      permission:
        columns: []
        filter:
          space:
            _or:
              - creator_id:
                  _eq: X-Hasura-User-Id
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
        check: null
  delete_permissions:
    - role: user
      permission:
        filter:
          space:
            _or:
              - creator_id:
                  _eq: X-Hasura-User-Id
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
- table:
    schema: public
    name: topic
  object_relationships:
    - name: room
      using:
        foreign_key_constraint_on: room_id
  array_relationships:
    - name: messages
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: message
          column_mapping:
            id: topic_id
  insert_permissions:
    - role: user
      permission:
        check:
          room:
            _and:
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
              - finished_at:
                  _is_null: true
        columns:
          - index
          - name
          - room_id
        backend_only: false
  select_permissions:
    - role: user
      permission:
        columns:
          - id
          - index
          - name
          - room_id
        filter:
          room:
            participants:
              user_id:
                _eq: X-Hasura-User-Id
        allow_aggregations: true
  update_permissions:
    - role: user
      permission:
        columns:
          - index
          - name
        filter:
          room:
            _and:
              - participants:
                  user_id:
                    _eq: X-Hasura-User-Id
              - finished_at:
                  _is_null: true
        check: null
  delete_permissions:
    - role: user
      permission:
        filter:
          room:
            participants:
              user_id:
                _eq: X-Hasura-User-Id
- table:
    schema: public
    name: transcription
  select_permissions:
    - role: user
      permission:
        columns:
          - created_at
          - id
          - status
          - transcript
          - updated_at
        filter: {}
- table:
    schema: public
    name: transcription_full_text
- table:
    schema: public
    name: transcription_status
  is_enum: true
- table:
    schema: public
    name: unread_messages
  select_permissions:
    - role: user
      permission:
        columns:
          - room_id
          - topic_id
          - unread_messages
        filter:
          user_id:
            _eq: X-Hasura-User-Id
- table:
    schema: public
    name: user
  array_relationships:
    - name: created_rooms
      using:
        foreign_key_constraint_on:
          column: creator_id
          table:
            schema: public
            name: room
    - name: invites
      using:
        foreign_key_constraint_on:
          column: inviter_id
          table:
            schema: public
            name: room_invites
    - name: messages
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: message
          column_mapping:
            id: user_id
    - name: rooms
      using:
        manual_configuration:
          remote_table:
            schema: public
            name: room_participants
          column_mapping:
            id: user_id
  select_permissions:
    - role: user
      permission:
        columns:
          - avatar_url
          - id
          - name
        filter: {}
        limit: 1
