-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notification" add column "notified_user_at" timestamptz
--  null;
