-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notification_slack_message" add column "slack_user_id" text
--  null;
