name: End-to-end test
on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: e2e-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --prefer-offline
      - run: npx playwright install
      - run: yarn workspace ~db generate
      - name: Setup dotenv
        run: cp .env.sample .env
      - run: docker-compose -f ./docker-compose.ci.yaml --env-file .env up -d
      - name: Run hasura migrations
        run: |
          sleep 5
          yarn hasura:migrations
          yarn hasura:seeds
          yarn hasura:meta
      - name: Start backend
        run: yarn workspace ~backend start:ci
      - name: Start frontend
        run: |
          yarn workspace ~frontend next:build
          yarn workspace ~frontend start:ci
      - name: Test Connection
        run: |
          curl -v localhost:3000/healthz
          curl -v localhost:1337/healthz
      - run: yarn e2e-tests test
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-artifacts
          path: end-to-end-tests/test-results/
