name: Kubernetes
on:
  push:
    paths:
      - "infrastructure/kubernetes/**"
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - run: ./kustomize cfg fmt ./infrastructure/kubernetes && git diff --exit-code
