name: Publish Desktop App
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-and-yarn
      - uses: actions/cache@v2
        with:
          path: |
            desktop/dist-staging
            desktop/dist-production
          key: desktop-dist-${{ github.sha }}
      - run: yarn build:bundle
      - run: yarn upload-sourcemaps
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-and-yarn
      - uses: actions/cache@v2
        with:
          path: |
            desktop/dist-staging
            desktop/dist-production
          key: desktop-dist-${{ github.sha }}
      - run: yarn desktop publish
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          GITHUB_TOKEN: ${{ secrets.GH_RELEASES_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          RELEASE_VERSION: ${{ github.ref_name }}
