name: Publish Desktop App
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-and-yarn
      - run: yarn desktop publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASES_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          RELEASE_VERSION: ${{ github.ref_name }}
